### ISSUE TITLE
Hello, I would like to ask you a question. Do these codes still apply if the reservoir contains side or bottom water?

### ISSUE THREAD

**Issue by Cythina12** [frank1010111/pywaterflood#6]

**Comment by frank1010111** [comment]
Hi @Cythina12, 
Yes, you can add a pseudowell to capture side or bottom water encroachment if you have estimates about their volumes.

**Comment by Cythina12** [comment]
> Hi @Cythina12, Yes, you can add a pseudowell to capture side or bottom water encroachment if you have estimates about their volumes.

Oh, okay, I understand, thank you very much for your answer, it is very beneficial to me.
